- client/src/components/Amount/AmountDetail.tsx
- client/src/components/Status/CategoryStatus.tsx
- client/src/components/Status/StatusCarousel.tsx
- client/src/components/Status/TotalStatus.tsx
- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/Transaction/TransactionItem.tsx
- client/src/components/Transaction/TransactionLayout.tsx
- client/src/components/Transaction/TransactionList.tsx
- client/src/models/Amount.ts
- client/src/models/Category.ts
- client/src/models/Transaction.ts
- client/src/screens/budget/BudgetDetail.tsx
- client/src/screens/budget/BudgetList.tsx
- client/src/screens/budget/TransactionDetail.tsx
- client/src/store/budget.ts
- client/src/store/category.ts
- client/src/store/index.ts
- client/src/store/transaction.ts
- Closes #2
- BudgetSlice - Initial State
```javascript
{
id: string;
title: string;
isRepeating: boolean;
startDate: Date;
endDate: Date;
total: Amount;
}[]
```
- TransactiontSlice - Initial State
```javascript
Transaction[]
```
- Transaction - Model Class
```javascript
{
id: string;
isCurrent: boolean;
isExpense: boolean;
title: string[];
date: Date;
amount: number;
categoryId: string;
tags?: string[];
icon?: string;
memo?: string;
}
```
- CategorySlice - Initial State
```javascript
Category[]
```
- Category - Model Class
```javascript
{
id: string;
title: string;
budgetId: string;
amounts: {[budgetId]: Amount};
icon?: string;
}
```
- `budgetActions.replaceTotalAmount`
- `budgetActions.updateTotalAmount`
- `categoryActions.updateAmount`
- `transactionActions.addTransaction`
- Component …
> Store / implement Budget, Transaction, Category state management

- client/src/components/Transaction/TransactionForm.module.css
- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/UI/input/CategoryInput.module.css
- client/src/components/UI/input/CategoryInput.tsx
- client/src/store/category.ts
- Closes #6 
- input
- select: diabled to make readOnly (for overriding default style)
- wrapper: onClick → open dropdown
- dropdown
- wrapper
- position absoulte relative to cateogry input-field
- height: 11.5rem
- ul
- height: 7.5rem
- li: onClick → select option
- li.button: onClick → open add category overlay
- overlay
- dispatch aciton: createCategory
- create category amount for current budget
> TransactionForm / create input component - Category

- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/UI/input/TitleInput.module.css
- client/src/components/UI/input/TitleInput.tsx
- client/src/store/transaction.ts
- Closes #12 
- Icon
- maxlength 2 for imogi _(TODO: validation)_
- Titles
- forward ref for multiple inputs (using imperativeHandle)
- responsively resize width by KeyUp event
- create & remove inputs
> TransactionForm / Create input compnent - Title

- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/UI/Tag.module.css
- client/src/components/UI/Tag.tsx
- client/src/components/UI/input/CategoryInput.module.css
- client/src/components/UI/input/TagInput.module.css
- client/src/components/UI/input/TagInput.tsx
- Closes #14 
- **forward ref:** transfer tagState
- **add:** space → add tag based on current input → clear input
- **remove:** backspace → remove last tag / onClick → remove target
> TransactionForm / Create input compnent - Tag

- client/src/components/UI/input/CategoryInput.tsx
- Closes #18 
- Check event target
- SPAN → get parentElement data Attribute as id
- onClick option → setIsExpand(false)
> CategoryInput / Resolve not selecting & closing issue

- server/.gitignore
- server/controllers/test.js
- server/index.js
- server/models/Test.js
- server/package.json
- server/routes/index.js
- server/routes/test.js
> Setup / Setup Basic Structure 

- server/.gitignore
- server/controllers/users.js
- server/index.js
- server/middleware/auth.js
- server/models/User.js
- server/package.json
- server/passport/index.js
- server/passport/localStrategy.js
- server/routes/index.js
- server/routes/users.js
> Authenciation / Setup session based authentication

- server/index.js
> fix: Update index.js to enable client to send a request

- server/controllers/categories.js
- server/models/User.js
- server/routes/categories.js
- server/routes/index.js
- Closes #29 
- Include 'categories' field in User model
- Create category APIs
- `POST /categories`: create category element
- `GET /categories`: read categories
- `PUT /cateogires/:_id`: update category element
- `PUT /cateogires/swap`:  swap category elements
- `Delete/cateogires/:id`: remove category element
> feat: Create Category APIs

- server/controllers/budgets.js
- server/controllers/categories.js
- server/controllers/transactions.js
- server/controllers/users.js
- server/middleware/auth.js
- server/models/Budget.js
- server/models/Transaction.js
- server/routes/budgets.js
- server/routes/index.js
- server/routes/transactions.js
- server/routes/users.js
- Closes #31
- Closes #32
- Closes #36 
- Closes #37 
- Closes #38
> Updaet Budget, Transaction, Category, Login APIs

- client/src/components/Amount/AmountDetail.tsx
- client/src/components/Status/TotalStatus.tsx
- client/src/components/Transaction/TransactionForm.tsx
- client/src/index.css
- client/src/index.tsx
- client/src/screens/ErrorBoundary.tsx
- client/src/screens/auth/Auth.module.css
- client/src/screens/auth/AuthForm.tsx
- client/src/screens/budget/Budget.tsx
- client/src/store/budget.ts
- client/src/util/api.ts
- Closes #48 
- Closes #49 
- #48
- Add `credential: 'include'` option in fetch request
- #49
- useRouteError
- useAsyncError for `<Await>`
> Fetch / Resolve cookie issue & Show error message

- client/src/components/Amount/AmountRing.module.css
- client/src/components/Amount/AmountRing.tsx
- client/src/components/UI/BarChart.module.css
- client/src/components/UI/BarChart.tsx
- client/src/models/Amount.ts
> TotalStatus / Handle over amount - change to bar chart

- client/src/components/Amount/AmountBar.module.css
- client/src/components/Amount/AmountBar.tsx
- client/src/components/Amount/AmountBars.tsx
- client/src/components/Amount/AmountDetail.tsx
- client/src/components/Amount/AmountRing.module.css
- client/src/components/Amount/AmountRing.tsx
- client/src/components/Budget/BudgetItem.module.css
- client/src/components/Budget/BudgetItem.tsx
- client/src/components/Status/TotalStatus.module.css
- client/src/components/Status/TotalStatus.tsx
- client/src/components/Transaction/TransactionNav.module.css
- client/src/index.css
- client/src/models/Amount.ts
- client/src/models/Category.ts
- client/src/store/budget.ts
> Status / Income chart

- client/src/components/Amount/AmountDetail.tsx
- client/src/components/Status/DateStatus.tsx
- client/src/components/Status/TotalStatus.tsx
- client/src/components/Transaction/TransactionNav.tsx
- client/src/components/UI/RadioTab.module.css
- client/src/components/UI/RadioTab.tsx
- client/src/index.css
- client/src/screens/budget/TransactionDetail.tsx
> RadioTab / Create component & Update using components

- client/src/store/transaction.ts
> Transaction / Sort by date (desc)

- server/.gitignore
- server/controllers/test.js
- server/controllers/users.js
- server/routes/test.js
- server/routes/users.js
> Auth / Update Authentication

- server/controllers/budgets.js
- server/models/Budget.js
- server/models/User.js
- server/routes/budgets.js
- Relates #62 
- Separate user.categories into user.expenseCategories and user.incomeCategories
- Separate budget.categories into budget.expenseCategories and budget.incomeCategories
- Update Category APIs
> Update User, Budget models and APIs

- client/src/index.tsx
- client/src/screens/auth/Auth.tsx
- client/src/util/api.ts
> Auth / Add auto login

- client/src/components/Amount/AmountRing.module.css
- client/src/components/Amount/AmountRing.tsx
- client/src/components/Budget/BudgetItem.module.css
- client/src/components/Budget/BudgetItem.tsx
- client/src/components/Budget/YearPicker.module.css
- client/src/components/Budget/YearPicker.tsx
- client/src/components/Status/TotalStatus.tsx
- client/src/components/Transaction/TransactionItem.tsx
- client/src/components/UI/BarChart.module.css
- client/src/index.css
- client/src/index.tsx
- client/src/models/Budget.ts
- client/src/screens/budget/Budget.tsx
- client/src/screens/budget/BudgetList.module.css
- client/src/screens/budget/BudgetList.tsx
- client/src/store/budget.ts
- client/src/util/api.ts
> BudgetList / Create screen

- server/controllers/categories.js
- Relates #69 
- 카테고리 조회 API
- `GET categories`
- 카테고리 생성 API
- `POST categories`
- 카테고리 수정 API
- `PUT categories/:categoryID`
- 해당 카테고리를 사용하는 budget과 transaction이 함께 변경됨
- 카테고리 swap API
-  `PUT categories/swap`
- 카테고리 삭제 API
- `DELETE categories/:categoryID`
- 해당 카테고리를 사용하는 budget이 있는 경우 삭제되지 않음
> feat: Update CategoryAPIs #69

- client/src/components/Status/CategoryStatus.tsx
- client/src/models/Category.ts
- client/src/screens/auth/Auth.tsx
- client/src/screens/budget/Budget.tsx
- client/src/store/category.ts
- client/src/store/transaction.ts
> Category / Fetch category

- client/src/components/Status/CategoryStatus.tsx
> CategoryStatus / Add RadioTab - expense, income

- client/src/models/Budget.ts
> Budget / Fix undefined error when updating total plan #78

- client/src/components/Amount/AmountDetail.tsx
- client/src/components/Status/TotalStatus.tsx
> AmountDetail / Make it reusable - dispatch in onEdit

- client/src/components/Amount/AmountBars.module.css
- client/src/components/Amount/AmountBars.tsx
- client/src/components/Amount/AmountDetail.module.css
- client/src/components/Amount/AmountDetail.tsx
- client/src/components/Status/CategoryStatus.module.css
- client/src/components/Status/CategoryStatus.tsx
- client/src/components/Status/TotalStatus.tsx
- client/src/store/category.ts
> CategoryStatus / Add AmountDetail

- server/controllers/budgets.js
- server/controllers/categories.js
- server/controllers/transactions.js
- server/models/Budget.js
- server/models/Transaction.js
- server/routes/budgets.js
> fix: Rename 'ammount' to 'amount' #85

- server/controllers/budgets.js
- server/controllers/transactions.js
- server/models/Budget.js
- server/models/Transaction.js
- server/routes/budgets.js
- server/routes/transactions.js
> 87 budget update budget model and apis

- server/controllers/budgets.js
> fix: Update DBudgetCategoryAPI #89

- client/src/components/Amount/AmountBars.module.css
- client/src/components/Status/CategoryStatus.tsx
- client/src/models/Budget.ts
- client/src/models/Category.ts
- client/src/store/budget.ts
- client/src/store/category.ts
- client/src/util/api.ts
> CategoryStatus / Get amount data & Update category plan

- client/src/components/Status/DateStatus.tsx
- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/Transaction/TransactionItem.tsx
- client/src/components/Transaction/TransactionList.tsx
- client/src/components/UI/Calendar.tsx
- client/src/models/Transaction.ts
- client/src/screens/budget/Budget.tsx
- client/src/store/budget.ts
- client/src/store/transaction.ts
- client/src/util/api.ts
> Transaction / CRUD transaction using API

- client/src/components/Transaction/TransactionForm.tsx
- client/src/models/Budget.ts
- client/src/models/Transaction.ts
- client/src/store/budget.ts
> fix: CategoryStatus / Update chart amount

- client/src/components/Amount/AmountRing.module.css
- client/src/components/Amount/AmountRing.tsx
- client/src/components/Budget/BudgetForm.module.css
- client/src/components/Budget/BudgetForm.tsx
- client/src/components/UI/Inform.module.css
- client/src/components/UI/Inform.tsx
- client/src/index.css
> BudgetForm / Inform left budget amount

- client/src/components/Transaction/TransactionItem.tsx
- client/src/store/transaction.ts
- client/src/util/api.ts
> Transaciton / Remove linkId

- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/Transaction/TransactionItem.module.css
- client/src/components/Transaction/TransactionItem.tsx
- client/src/models/Transaction.ts
- client/src/util/api.ts
> Transaction / Inform overAmount

- client/src/components/Transaction/TransactionForm.module.css
- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/Transaction/TransactionNav.module.css
- client/src/components/Transaction/TransactionNav.tsx
- client/src/store/ui.ts
> TransactionForm / Add type field

- client/src/index.tsx
- client/src/screens/Nav.module.css
- client/src/screens/Nav.tsx
> feat: Nav / Create bottom nav bar to Root

- client/src/components/Category/CategoryForm.module.css
- client/src/components/Category/CategoryForm.tsx
- client/src/components/Status/CategoryStatus.module.css
- client/src/components/Status/CategoryStatus.tsx
- client/src/components/UI/form/OverlayForm.tsx
- client/src/store/ui.ts
> CategoryForm / Create category management form

- server/controllers/categories.js
- server/models/User.js
> Categories / Default Categories

- client/src/App.css
> feat: Style / Set global style

- client/src/components/UI/InputField.tsx
- client/src/components/auth/CodeField.tsx
- client/src/components/auth/LoginForm.tsx
- client/src/components/auth/RegisterForm.module.css
- client/src/components/auth/RegisterForm.tsx
> Auth / Focus to input

- client/package-lock.json
- client/package.json
- client/src/index.tsx
- client/src/store/index.ts
- client/src/util/api.ts
> Fetch / Set for fetching data

- server/models/User.js
> feat: Update default category settings #114

- client/public/index.html
- client/src/App.tsx
- client/src/components/auth/LoginForm.tsx
- client/src/screens/Nav.module.css
- client/src/screens/Nav.tsx
> Nav / Add main nav bar

- client/src/App.tsx
- client/src/models/Amount.ts
- client/src/models/Budget.ts
- client/src/models/Category.ts
- client/src/screens/BudgetNavigation.tsx
- client/src/store/budget.ts
- client/src/store/index.ts
- client/src/util/api/budgetAPI.ts
> Budget / Fetch budget list & navigate to current budget

- server/controllers/categories.js
- server/models/User.js
- server/routes/categories.js
- server/utils/compareById.js
> 137 category update api

- client/src/App.tsx
- client/src/components/Budget/BudgetHeader.module.css
- client/src/components/Budget/BudgetHeader.tsx
- client/src/components/UI/NavButton.tsx
- client/src/screens/Budget.tsx
- client/src/util/date.ts
> Budget / Create BudgetHeader component

- client/src/components/Status/CategoryStatus.tsx
- client/src/components/Status/DateStatus.tsx
- client/src/components/Status/TotalStatus.tsx
- client/src/components/UI/Carousel.module.css
- client/src/components/UI/Carousel.tsx
- client/src/screens/Budget.module.css
- client/src/screens/Budget.tsx
> Budget / Add status layout

- server/controllers/budgets.js
- server/models/Budget.js
> 143 budget default category

- server/controllers/users.js
- server/models/User.js
- server/passport/localStrategy.js
- server_db/src/pages/UserPage/List.js
> feat: Replace field 'userName' with 'email' #132

- client/src/App.tsx
- client/src/components/auth/LoginForm.tsx
- client/src/components/auth/RequireAuth.tsx
- client/src/screens/Auth.tsx
- client/src/screens/ErrorBoundary.tsx
- client/src/screens/Nav.tsx
- client/src/util/api/userAPI.ts
> Auth / Protect page

- client/src/App.css
- client/src/components/Amount/AmountBar.module.css
- client/src/components/Amount/AmountBar.tsx
- client/src/components/Amount/AmountBars.module.css
- client/src/components/Amount/AmountBars.tsx
- client/src/components/Amount/AmountDetail.module.css
- client/src/components/Status/CategoryStatus.tsx
- client/src/components/Status/CategoryStatusNav.module.css
- client/src/components/Status/CategoryStatusNav.tsx
- client/src/components/Status/StatusHeader.module.css
- client/src/components/Status/StatusHeader.tsx
- client/src/models/Budget.ts
- client/src/screens/Budget.module.css
- client/src/screens/Budget.tsx
> Status / Create CateogyStatus component

- server/controllers/budgets.js
> feat: Remove transactions when budget is removed #163

- server/controllers/budgets.js
- server/controllers/test.js
- server/controllers/transactions.js
- server/routes/test.js
- server_db/src/pages/BudgetPage/List.js
> feat: Update related docs when removing doc #164

- server/controllers/transactions.js
- server/models/Transaction.js
- server_db/src/pages/BudgetPage/tab/TransactionList.js
> Transaction / Add field 'overAmount'

- server/controllers/budgets.js
- server/controllers/categories.js
- server/controllers/transactions.js
- server/models/Budget.js
- server/models/User.js
- server/routes/categories.js
- server_db/src/pages/BudgetPage/tab/Categories.js
- server_db/src/pages/UserPage/tab/Categories.js
> Category / Allow category "expense" or "income" only

- client/src/components/Status/CategoryStatus.tsx
- client/src/components/Status/DateStatus.module.css
- client/src/components/Status/DateStatus.tsx
- client/src/components/Status/StatusHeader.tsx
- client/src/components/UI/Calendar.module.css
- client/src/components/UI/Calendar.tsx
- client/src/screens/Budget.tsx
- client/src/util/date.ts
> Status / Create DateStatus component

- client/src/App.css
- client/src/components/Transaction/TransactionForm.module.css
- client/src/components/Transaction/TransactionForm.tsx
- client/src/components/Transaction/TransactionLayout.tsx
- client/src/components/Transaction/TransactionList.module.css
- client/src/components/UI/InputField.module.css
- client/src/components/UI/OverlayForm.module.css
- client/src/components/UI/OverlayForm.tsx
> Transaction / Add form layout

- client/package.json
- client/src/components/UI/input/EmojiInput.module.css
- client/src/components/UI/input/EmojiInput.tsx
> Emoji / Create EmojiInput component

- client/package-lock.json
- client/src/components/Budget/Input/EmojiInput.module.css
- client/src/components/Budget/Input/EmojiInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/Overlay.module.css
- client/src/components/UI/Overlay.tsx
> EmojiInput / Update style - overlay, open animation

- client/src/App.tsx
- client/src/components/Budget/Transaction/TransactionItem.module.css
- client/src/components/Budget/Transaction/TransactionItem.tsx
- client/src/components/UI/Icon.module.css
- client/src/components/UI/Icon.tsx
- client/src/components/User/Profile/UserHeader.module.css
- client/src/components/User/Profile/UserHeader.tsx
- client/src/components/User/Setting/SettingItem.module.css
- client/src/components/User/Setting/SettingItem.tsx
- client/src/components/User/Setting/SettingList.module.css
- client/src/components/User/Setting/SettingList.tsx
- client/src/screens/User.module.css
- client/src/screens/User.tsx
> User / Create Layout

- server/controllers/test.js
- server/controllers/users.js
- server/index.js
- server/package.json
- server/redis/index.js
- server/routes/users.js
- server/utils/crypto.js
- server/utils/generateRandomNumber.js
- server/utils/sendEmail.js
> 156 verify email

- client/src/App.css
- client/src/components/Budget/Input/CategoryInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/Button.module.css
- client/src/components/UI/Button.tsx
- client/src/components/UI/Select.module.css
- client/src/components/UI/Select.tsx
> UI / Create SelectInput

- server/controllers/transactions.js
> fix: Update transaction amount update API #186

- client/src/App.css
- client/src/components/Budget/Input/AmountInput.tsx
- client/src/components/Budget/Input/CategoryInput.tsx
- client/src/components/Budget/Input/EmojiInput.tsx
- client/src/components/Budget/Transaction/OverAmountMsg.module.css
- client/src/components/Budget/Transaction/OverAmountMsg.tsx
- client/src/components/Budget/Transaction/TransactionDetail.module.css
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionItem.module.css
- client/src/components/Budget/Transaction/TransactionItem.tsx
- client/src/components/Budget/Transaction/TransactionLayout.tsx
- client/src/components/Budget/Transaction/TransactionList.module.css
- client/src/components/Budget/Transaction/TransactionList.tsx
- client/src/components/Budget/Transaction/TransactionNav.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
- client/src/components/Budget/UI/ExpenseTab.tsx
- client/src/components/UI/Icon.tsx
- client/src/components/UI/OptionButton.module.css
- client/src/components/UI/OptionButton.tsx
- client/src/components/UI/Overlay.module.css
- client/src/components/UI/Overlay.tsx
- client/src/components/UI/Select.module.css
- client/src/components/UI/Select.tsx
- client/src/models/Transaction.ts
- client/src/store/budget.ts
- client/src/store/index.ts
- client/src/store/transaction.ts
- client/src/store/ui.ts
- client/src/util/api/transactionAPI.ts
> Transaction / Implement read, update, delete, complete

- client/src/components/Budget/Status/DateStatus.tsx
> feat: DateStatus / Implement view, add action #118

- client/src/components/Budget/Input/TagInput.module.css
- client/src/components/Budget/Input/TagInput.tsx
- client/src/components/UI/Tag.module.css
- client/src/components/UI/Tag.tsx
- client/src/store/transaction.ts
> TagInput / Implement tag input

- client/src/components/Budget/Input/TagInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> TransactionForm / Scroll & focus

- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
- client/src/util/api/transactionAPI.ts
> feat: Transaction / Scroll when created, view other transaction

- client/src/components/Budget/Amount/AmountDetail.tsx
- client/src/components/Budget/Amount/AmountDetailItem.module.css
- client/src/components/Budget/Amount/AmountDetailItem.tsx
- client/src/components/Budget/Status/CategoryStatus.tsx
- client/src/components/Budget/Status/TotalStatus.tsx
- client/src/models/Amount.ts
- client/src/models/Budget.ts
- client/src/screens/Budget.tsx
- client/src/store/budget.ts
- client/src/util/api/budgetAPI.ts
> AmountDetail / Add edit mode

- server/controllers/transactions.ts
- server/models/Transaction.ts
- server_db/src/pages/BudgetPage/tab/TransactionList.js
- server_db/src/pages/TransactionPage/List.js
- server_db/src/pages/UserPage/tab/TransactionList.js
> Transaction / Add field 'icon'

- server/controllers/users.ts
- server/models/User.ts
- server/routes/users.ts
> User / Add fields('birthdate', 'gender', 'tel') to user model and create update API

- server/controllers/users.ts
- server/models/User.ts
- server/package.json
- server/passport/guestStrategy.ts
- server/passport/index.ts
- server/passport/localStrategy.ts
- server/passport/registerStrategy.ts
- server/routes/users.ts
> User / remove field 'password'

- client/.gitignore
- client/src/components/Budget/Amount/IncomeExpenseAmount.module.css
- client/src/components/Budget/Amount/IncomeExpenseAmount.tsx
- client/src/components/Budget/Chart/GroupedBar.module.css
- client/src/components/Budget/Chart/GroupedBar.tsx
- client/src/components/Budget/Chart/IncomeExpenseGroupedChart.module.css
- client/src/components/Budget/Chart/IncomeExpenseGroupedChart.tsx
- client/src/components/Budget/Date/MonthlyStatus.tsx
- client/src/components/Budget/Date/WeeklyStatus.module.css
- client/src/components/Budget/Date/WeeklyStatus.tsx
- client/src/components/Budget/Status/DateStatus.module.css
- client/src/components/Budget/Status/DateStatus.tsx
- client/src/components/Budget/Transaction/TransactionDetail.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionList.module.css
- client/src/components/UI/Calendar.module.css
- client/src/components/UI/Calendar.tsx
- client/src/components/UI/IndexNav.module.css
- client/src/components/UI/IndexNav.tsx
- client/src/screens/Budget.tsx
- client/src/util/date.ts
> DateStatus / Update DateStatus - weekly chart

- client/src/App.css
- client/src/components/Budget/Amount/AmountBar.module.css
- client/src/components/Budget/Amount/AmountBars.module.css
- client/src/components/Budget/Amount/AmountRing.module.css
- client/src/components/Budget/Chart/GroupedBar.module.css
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/UI/InputField.module.css
- client/src/components/UI/Overlay.module.css
- client/src/components/UI/Select.module.css
- client/src/store/transaction.ts
> feat: Transition / Update transition using cubic-bezier

- server/controllers/budgets.ts
- server/controllers/categories.ts
> Category / Enable to update default category title and icon

- client/src/components/Budget/Category/BudgetCategorySetting.module.css
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanList.tsx
- client/src/components/Budget/Chart/IncomeExpenseGroupedChart.tsx
- client/src/components/Budget/Status/CategoryStatus.tsx
- client/src/components/Budget/Status/TotalStatus.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/User/Category/UserCategoryItem.tsx
- client/src/components/User/Category/UserCategoryList.module.css
- client/src/components/User/Category/UserCategoryList.tsx
- client/src/models/Amount.ts
- client/src/store/budget.ts
- client/src/util/api/budgetAPI.ts
- client/src/util/api/transactionAPI.ts
> Test / Fix category & amount issue

- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Input/EditInput.tsx
> CategoryPlan / Fix plan update, add blur event when edit total

- server/controllers/budgets.ts
- server/controllers/transactions.ts
- server/routes/budgets.ts
- server/routes/transactions.ts
- server_db/src/hooks/useAPI.js
- server_db/src/pages/BudgetPage/Index.js
- server_db/src/pages/BudgetPage/tab/Validate.js
> Transaction / Enable to update at once

- client/src/components/Budget/Amount/AmountDetailItem.module.css
- client/src/components/Budget/Amount/AmountDetailItem.tsx
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.module.css
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Input/CategoryInput.module.css
- client/src/components/Budget/Input/CategoryInput.tsx
- client/src/components/Budget/Input/EditInput.module.css
- client/src/components/Budget/Input/EditInput.tsx
- client/src/components/Budget/Status/CategoryStatus.module.css
- client/src/components/Budget/Status/CategoryStatus.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionLayout.tsx
- client/src/components/Budget/UI/ExpenseTab.tsx
- client/src/components/UI/RadioTab.tsx
- client/src/components/UI/Select.module.css
- client/src/components/UI/Select.tsx
- client/src/components/User/Category/UserCategoryList.tsx
- client/src/models/Amount.ts
- client/src/screens/Auth.tsx
- client/src/screens/Budget.tsx
- client/src/screens/User.module.css
- client/src/screens/User.tsx
- client/src/store/transaction.ts
- client/src/store/ui.ts
- client/src/store/user.ts
- client/src/util/api/transactionAPI.ts
- client/src/util/api/userAPI.ts
> TransactionForm, Status, Setting / Enhance

- server/.gitignore
- server/controllers/assets.ts
- server/controllers/budgets.ts
- server/controllers/cards.ts
- server/controllers/categories.ts
- server/controllers/paymentMethods.ts
- server/controllers/test.ts
- server/controllers/transactions.ts
- server/controllers/users.ts
- server/index.ts
- server/log/logger.ts
- server/middleware/auth.ts
- server/package.json
- server/routes/budgets.ts
> Log / Create basic logging system 

- .github/workflows/server-pipeline.yml
- server/Dockerfile
- server/index.ts
- server/package.json
> Prod / Update .env settings & scripts

- .github/workflows/client-pipeline.yml
- .github/workflows/server-pipeline.yml
- server/.gitignore
- server/@types/index.d.ts
- server/Dockerfile
- server/controllers/assets.ts
- server/controllers/cards.ts
- server/controllers/categories.ts
- server/controllers/paymentMethods.ts
- server/index.ts
- server/package.json
- server/tsconfig.json
- server/utils/email.ts
> Deployment / Deploy

- server/controllers/transactions.ts
> Transaction / Fix transaction update bug

- .github/workflows/server-pipeline.yml
- server/@types/env.d.ts
- server/@types/s3-streamlogger-daily/index.d.ts
- server/Dockerfile
- server/index.ts
- server/log/devLogger.ts
- server/log/logger.ts
- server/log/prodLogger.ts
- server/middleware/auth.ts
- server/package.json
> Log / Upload log to AWS s3

- server/controllers/budgets.ts
- server/controllers/categories.ts
- server/routes/budgets.ts
- server/routes/categories.ts
> Categories / Create user categoires partially update API

- server/index.ts
- server/log/devLogger.ts
- server/log/prodLogger.ts
> Log / Update production logger

- server/log/prodLogger.ts
- server_Lambda/.gitignore
- server_Lambda/index.js
- server_Lambda/package.json
> Log / Archive log daily

- server/controllers/budgets.ts
> Budget / Find budget by date

- server/controllers/transactions.ts
- server/models/Budget.ts
> Transaction / Update APIs

- server/controllers/transactions.ts
> Transaction / Fix update error

- server/controllers/assets.ts
- server/controllers/cards.ts
- server/controllers/transactions.ts
- server/models/Transaction.ts
- server/models/User.ts
- server/routes/index.ts
- server_db/src/pages/UserPage/tab/AssetsAndCards.js
- server_db/src/pages/UserPage/tab/PaymentMethods.js
- server_db/src/popups/Transaction.js
> Asset&Card / Add field 'detail'

- server/controllers/transactions.ts
- server/models/Transaction.ts
> Transaction / Add field 'updateAsset`

- server/controllers/assets.ts
- server/controllers/cards.ts
- server/controllers/paymentMethods.ts
- server/models/User.ts
- server_db/src/pages/UserPage/tab/PaymentMethods.js
> PaymentMethod / Add field `isChecked`

- server/controllers/assets.ts
- server/routes/assets.ts
> Asset / Create single asset C/U/D APIs

- server/controllers/users.ts
- server/routes/users.ts
> User / Create DUser API 

- client/src/App.tsx
- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Asset/Editor/CardFields.tsx
- client/src/components/Budget/List/BudgetItem.tsx
- client/src/components/Budget/Status/TotalStatus.tsx
- client/src/components/Budget/UI/BudgetHeader.tsx
- client/src/components/Budget/UI/BudgetNav.tsx
- client/src/components/User/Default/DefaultStatus.module.css
- client/src/screens/Budget.tsx
- client/src/screens/NewBudget.module.css
- client/src/screens/NewBudget.tsx
> Budget / Implement new budget

- client/src/components/Budget/List/BudgetItem.tsx
- client/src/components/Budget/Status/TotalStatus.tsx
> AmountRing / Set dash for different screen size

- client/src/components/UI/Carousel.tsx
> Carousel / Fix initial index setting

- client/src/components/Budget/Status/CategoryStatus.tsx
> CategoryStatus / Fix index bug (expense <-> income)

- client/src/components/Budget/Amount/AmountRing.module.css
- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/Budget/Amount/Ring.tsx
- client/src/models/Amount.ts
> Ring / Remove filter & Add opacity animation

- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/Overlay.module.css
> Overlay / Change transition property for optimization

- server/controllers/budgets.ts
> Admin / Fix loading budgets error

- server/controllers/cards.ts
- server/routes/cards.ts
> Card / Create C/U/D APIs

- client_admin/src/components/Loading.js
- client_admin/src/components/Tabs.js
- client_admin/src/pages/BudgetPage/List.js
- client_admin/src/pages/BudgetPage/tab/BasicInfo.js
- client_admin/src/pages/BudgetPage/tab/Categories.js
- client_admin/src/pages/BudgetPage/tab/TransactionList.js
- client_admin/src/pages/BudgetPage/tab/Validate.js
- client_admin/src/pages/TransactionPage/List.js
- client_admin/src/pages/UserBudgetPage/tab/BasicInfo.js
- client_admin/src/pages/UserBudgetPage/tab/Categories.js
- client_admin/src/pages/UserBudgetPage/tab/TransactionList.js
- client_admin/src/pages/UserBudgetPage/tab/Validate.js
- client_admin/src/pages/UserPage/List.js
- client_admin/src/pages/UserPage/tab/Assets.js
- client_admin/src/pages/UserPage/tab/BasicInfo.js
- client_admin/src/pages/UserPage/tab/BudgetList.js
- client_admin/src/pages/UserPage/tab/Cards.js
- client_admin/src/pages/UserPage/tab/Categories.js
- client_admin/src/pages/UserPage/tab/PaymentMethods.js
> Admin / Create Loading component

- client_admin/src/pages/BudgetPage/tab/TransactionList.js
- client_admin/src/pages/TransactionPage/List.js
- client_admin/src/pages/UserBudgetPage/tab/TransactionList.js
> Admin / Fix loading transactions error

- client/src/App.tsx
> Sentry / Start logging

- client/src/components/UI/DraggableList.tsx
- client/src/screens/User.tsx
> DraggableList / Add renderClone for fixed-transform issue

- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/Overlay.module.css
> BudgetCategorySetting: Move to outside of TransactionForm

- server/controllers/transactions.ts
> Transaction / return updated transactionScheduled #312

- client/src/components/Budget/Input/MemoInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/store/transaction.ts
- client/src/util/api/transactionAPI.ts
- client/vite.config.ts
> Transaction / Add updateAsset field

- client/src/components/Asset/Editor/PaymentEditor.module.css
- client/src/components/Asset/Editor/PaymentEditor.tsx
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionItem.tsx
- client/src/components/UI/ConfirmCancelButtons.module.css
- client/src/components/UI/DraggableItem.module.css
- client/src/components/UI/DraggableItem.tsx
- client/src/components/UI/DraggableList.tsx
- client/src/components/UI/Overlay.module.css
- client/src/components/UI/Select.module.css
- client/src/components/UI/Select.tsx
- client/src/store/transaction.ts
- client/src/util/api/assetAPI.ts
- client/src/util/api/transactionAPI.ts
> Payment / Implement payment method list & fields & editor

- client/src/components/Asset/Editor/PaymentEditor.module.css
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/store/transaction.ts
- client/src/util/api/transactionAPI.ts
> PaymentEditor / Fix dispatch & Update style

- client/package.json
- client/src/App.tsx
- client/src/layout/ErrorBoundary.tsx
- client/src/screens/Auth.tsx
> ErrorBoundary / Change <Navigate /> to useNavigate()

- client_admin/src/components/Navbar.js
- client_admin/src/pages/UserPage/Index.js
- client_admin/src/pages/UserPage/tab/Settings.js
- server/controllers/settings.ts
- server/models/User.ts
- server/routes/index.ts
- server/routes/settings.ts
> User / Add field 'settings'

- client_admin/src/pages/BudgetPage/tab/Categories.js
- client_admin/src/pages/UserBudgetPage/tab/Categories.js
- server/models/User.ts
> User & Budget / Update default categoreis and include them in basic budget

- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/screens/Auth.tsx
- client/src/store/index.ts
- client/src/store/setting.ts
- client/src/store/user.ts
- client/src/util/api/settingAPI.ts
- client/src/util/api/userAPI.ts
> feat: ChartSkin / Fetch setting data

- client/src/components/Budget/Input/CategoryInput.tsx
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionLayout.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
- client/src/components/User/Default/DefaultStatus.tsx
- client/src/store/transaction.ts
> CategoryInput / Refactor isExpense & setIcon

- client/src/components/Budget/Input/AmountInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/Overlay.tsx
> TransactionForm / Prevent scroll on focus amountInput & Show only button in short mode (quick fix)

- client/src/App.css
- client/src/components/Budget/Category/BudgetCategorySetting.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/ConfirmCancelButtons.module.css
- client/src/components/UI/ConfirmCancelButtons.tsx
> TransactionForm / Add pending state  

- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Asset/Editor/PaymentEditor.tsx
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/List/BudgetItem.tsx
- client/src/components/Budget/List/BudgetList.tsx
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/EmojiOverlay.tsx
- client/src/components/UI/Overlay.module.css
- client/src/components/UI/Overlay.tsx
- client/src/components/User/Category/UserCategorySetting.tsx
- client/src/components/User/Skin/ChartSkinSetting.tsx
> Overlay / Add transform-translateY overlay for optimization

- client/src/components/Asset/Editor/AssetCardItemEditor.module.css
- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Asset/Editor/AssetCardListEditor.module.css
- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Asset/Editor/PaymentEditor.module.css
- client/src/components/Asset/Editor/PaymentEditor.tsx
- client/src/components/Budget/Category/BudgetCategorySetting.module.css
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.module.css
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/ConfirmCancelButtons.tsx
- client/src/components/UI/Overlay.tsx
- client/src/components/UI/OverlayForm.module.css
- client/src/components/UI/OverlayForm.tsx
- client/src/components/UI/Select.module.css
- client/src/components/UI/Select.tsx
- client/src/components/User/Category/UserCategorySetting.module.css
- client/src/components/User/Category/UserCategorySetting.tsx
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/screens/Asset.tsx
- client/src/util/api/assetAPI.ts
- client/vite.config.ts
> OverlayForm / Create OverlayForm component

- client/src/components/Asset/Editor/AssetCardListEditor.tsx
> AssetCardListEditor / Check if response exists in submitHandler

- client/src/components/UI/EmojiOverlay.module.css
- client/src/components/UI/Modal.module.css
- client/src/components/UI/Modal.tsx
- client/src/screens/Auth.tsx
- client/src/screens/Budget.tsx
- client/src/screens/InitialSetting.tsx
- client/src/screens/NewBudget.tsx
- client/src/screens/User.tsx
- client/src/store/ui.ts
> Modal / Create modal component

- client/src/components/UI/Modal.module.css
- client/src/components/UI/Modal.tsx
- client/src/screens/Auth.tsx
- client/src/screens/Redirect.tsx
- client/src/screens/User.tsx
- client/src/store/ui.ts
> Redirect / User modal for sns direct

- client/src/screens/User.module.css
- client/src/screens/User.tsx
- client/src/util/api/userAPI.ts
> User / Add delete user button

- client/src/components/Auth/EmailForm.module.css
- client/src/components/Auth/EmailForm.tsx
- client/src/components/Auth/SNSForm.tsx
- client/src/components/UI/Inform.module.css
- client/src/components/UI/Inform.tsx
- client/src/components/UI/OverlayForm.tsx
- client/src/screens/Auth.tsx
- client/src/util/api/userAPI.ts
- client/src/util/error.ts
- client/src/util/validate.ts
> Auth / Show error message

- client/src/App.css
- client/src/components/Auth/EmailForm.module.css
- client/src/components/Auth/EmailForm.tsx
> Auth / Lock email input & Add persist option

- server/controllers/budgets.ts
- server/controllers/transactions.ts
- server/models/Budget.ts
> Budget / Create fields `expenseScheduledRemain` & `incomeScheduledRemain` 

- client/src/components/Budget/Input/PaymentInput.module.css
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/UI/Select.tsx
> PaymentInput / Add tab - asset, card

- client/src/models/Budget.ts
- client/src/store/total.ts
- client/src/util/api/budgetAPI.ts
> Amount / Use scheduledRemain

- client/src/components/Budget/Transaction/TransactionDetail.tsx
> TransactionDetail / Fix handler empty transaction on first load

- client_admin/src/pages/LogInPage/Index.js
- client_admin/src/pages/LogInPage/Index_save.js
- server/controllers/users.ts
> Auth / Fix local login bug

- client/src/screens/Redirect.tsx
- client/src/util/api/userAPI.ts
- client/src/util/error.ts
> Auth / Update error message according to server change

- client/src/components/Budget/Transaction/TransactionForm.module.css
> TransactionForm / Fix defaultBudget style (height -> transform)

- server/controllers/budgets.ts
- server/controllers/users.ts
> fix: Fix 0_FIELD_REQUIRED bug #386

- client/src/components/Auth/Auth.tsx
- client/src/components/Auth/EmailForm.tsx
- client/src/components/Auth/GuestLoginButton.tsx
- client/src/components/Auth/SNSForm.tsx
- client/src/screens/InitialSetting.tsx
- client/src/screens/Landing.tsx
- client/src/screens/Redirect.tsx
- client/src/util/api/userAPI.ts
- Closes #341
- Fix resetting isVerify
> Auth / Let user init & Add guest login

- client/src/components/Budget/Input/DateInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> DateInput / Enable time setting

- client/src/components/Asset/Editor/AssetCardEditItemList.tsx
- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Auth/Auth.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
- client/src/components/UI/DraggableItem.tsx
- client/src/components/UI/Modal.module.css
- client/src/components/UI/Modal.tsx
- client/src/layout/Root.tsx
- client/src/screens/Budget.tsx
- client/src/screens/InitialSetting.tsx
- client/src/screens/NewBudget.tsx
- client/src/screens/User.tsx
- client/src/store/ui.ts
> Modal / Add & use confirm feature

- client/src/components/Budget/Category/CategoryPlan.module.css
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanItem.module.css
- client/src/components/Budget/Category/CategoryPlanItem.tsx
> CategoryPlan / Show possible plan amount & Show default in list

- client/src/components/Budget/Transaction/TransactionGroup.module.css
- client/src/components/Budget/Transaction/TransactionGroup.tsx
- client/src/components/Budget/Transaction/TransactionItem.module.css
- client/src/components/Budget/Transaction/TransactionItem.tsx
- client/src/components/Budget/Transaction/TransactionList.module.css
- client/src/components/Budget/Transaction/TransactionList.tsx
- client/src/components/Budget/Transaction/TransactionNav.module.css
- client/src/components/Budget/Transaction/TransactionNav.tsx
- client/src/components/Budget/UI/ExpenseTab.tsx
- client/src/screens/Budget.tsx
> TransactionList / Show schduled & current together + folding

- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Asset/List/CardList.tsx
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/UI/DraggableItem.tsx
- client/src/components/UI/RadioTab.tsx
- client/src/components/UI/Select.tsx
- client/src/screens/Asset.tsx
- client/src/screens/InitialSetting.tsx
> AssetCard / Fix UI bugs

- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/models/Amount.ts
> Amount / Update overAmount logic based on scheduledRemain

- client/src/components/Budget/Transaction/TransactionForm.tsx
> TransactionForm / Fix isCurrent bug & payment bug

- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
> fix: TransactionOption / Check if asset exists when dispatch after remove

- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanItem.tsx
> CategoryPlan / Update default category state

- client/src/models/Amount.ts
> Amount / Fix available schedule amount #423

- client/src/components/UI/OverlayForm.tsx
- client/src/components/User/Skin/ChartSkinSetting.tsx
> OverlayForm / Fix pending not awaited error

- .github/workflows/server-pipeline.yml
- server/@types/env.d.ts
- server/controllers/auth.ts
- server/passport/googleStrategy.ts
> Auth / Auto login with social login

- server/controllers/transactions.ts
> fix: Fxi RTransactions API #395

- client_admin/src/pages/BudgetPage/List.js
- client_admin/src/pages/UserPage/tab/BudgetList.js
- server/app.ts
- server/controllers/budgets.ts
- server/controllers/settings.ts
- server/controllers/transactions.ts
- server/index.ts
- server/models/Budget.ts
- server/models/User.ts
- server/models/_basicSettings.ts
- server/models/_chartSkin.ts
- server/package.json
- server/routes/index.ts
- server/routes/settings.ts
- server/routes/test.ts
> User / Setting timezone

- client/src/models/Budget.ts
- client/src/util/api/budgetAPI.ts
> fix: Budget / Update year & month field

- .github/workflows/client-pipeline.yml
- client/src/App.tsx
- client/src/components/Asset/Editor/AssetCardItemEditor.module.css
- client/src/components/Asset/Editor/AssetCardListEditor.module.css
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Payment/PaymentOverlay.module.css
- client/src/components/Payment/PaymentOverlay.tsx
- client/src/components/UI/OverlayForm.module.css
- client/src/components/UI/OverlayForm.tsx
- client/src/components/User/Category/UserCategorySetting.tsx
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/layout/AuthRedirect.tsx
- client/src/layout/ErrorBoundary.tsx
- client/src/layout/PaymentRedirect.tsx
- client/src/screens/User.tsx
- client/src/store/ui.ts
- client/src/types/global.d.ts
- client/src/types/portone.ts
> PaymentOverlay / Create component

- client/src/App.tsx
- client/src/models/Category.ts
- client/src/util/api/categoryAPI.ts
> Category / Update scheduledRemain

- server/controllers/auth.ts
> Auth / Update auth redirect url 

- client/src/components/Budget/Amount/AmountBars.tsx
> fix: AmountBars / Hide zero amount bar

- client/src/components/Asset/Editor/AssetCardEditItemList.module.css
- client/src/components/Asset/Editor/AssetCardEditItemList.tsx
- client/src/components/Asset/Editor/AssetCardItemEditor.module.css
- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Asset/Editor/CardFields.tsx
- client/src/components/Asset/Status/AssetStatus.module.css
- client/src/components/Asset/Status/AssetStatus.tsx
- client/src/components/Asset/Status/CardStatus.module.css
- client/src/components/Asset/Status/CardStatus.tsx
- client/src/components/Auth/Auth.module.css
- client/src/components/Budget/Input/DateInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.module.css
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/screens/InitialSetting.module.css
- client/src/screens/InitialSetting.tsx
> Init / Update initial setting enhancements

- server/_passportConfig/localV2Strategy.ts
> fix: Reuse email to local login #472

- client/src/components/Budget/Input/TagInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> fix: TagInput / Enable '#' input

- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/UI/RadioTab.tsx
> fix: PaymentInput / Enable only assest when isIncome #459

- .github/workflows/server-pipeline.yml
- client_admin/src/pages/App.js
- client_admin/src/pages/ItemPage/Index.js
- client_admin/src/pages/LandingPage/Index.js
- client_admin/src/pages/UserPage/Index.js
- client_admin/src/pages/UserPage/tab/Payments.js
- server/@message/index.ts
- server/@types/env.d.ts
- server/app.ts
- server/controllers/items.ts
- server/controllers/payments.ts
- server/controllers/settings.ts
- server/middleware/auth.ts
- server/models/Item.ts
- server/models/Payment.ts
- server/package.json
- server/routes/index.ts
- server/routes/items.ts
- server/routes/payments.ts
> Payment / 결제 기능 구현

- server/controllers/users.ts
> User / Enable to update userName 

- client/src/components/Payment/PaymentOverlay.module.css
- client/src/components/Payment/PaymentOverlay.tsx
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/store/ui.ts
- client/src/util/api/itemAPI.ts
- client/src/util/api/paymentAPI.ts
> feat: Pay / Add prepare & complete payment process

- client/src/components/Budget/Input/DateInput.tsx
- client/src/components/Budget/Input/DateSelector.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> feat: DateSelector / Add dateSelector for basic budget

- client/src/components/Asset/Editor/AssetFields.tsx
- client/src/components/Budget/Input/EditInput.tsx
> fix: AmountInput / Handle focus & blur on 0 value

- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/DefaultCategoryEdit.module.css
- client/src/components/Budget/Category/DefaultCategoryEdit.tsx
- client/src/components/User/Category/UserCategoryList.module.css
- client/src/components/User/Category/UserCategoryList.tsx
> CategorySetting / Update default category in draggableList

- client_admin/src/pages/UserPage/tab/Payments.js
- server/controllers/payments.ts
- server/controllers/settings.ts
- server/middleware/auth.ts
> Payment / Test APIs

- client/src/components/Budget/Amount/AmountDetailItem.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Input/EditInput.tsx
- client/src/components/User/Default/DefaultStatus.module.css
- client/src/components/User/Default/DefaultStatus.tsx
> feat: Init / Focus planEditor when setting default budget

- client/index.html
- client/src/components/Ad/GoogleAdsense.tsx
- client/src/types/global.d.ts
> feat: Adsense / Add google adsense & analytics #494

- client/src/components/Budget/Date/MonthlyStatus.tsx
- client/src/components/Budget/Transaction/TransactionGroup.tsx
> fix: TransactionGroup / Expand on default #496

- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Asset/Editor/CardFields.tsx
- client/src/components/Asset/List/AssetList.tsx
- client/src/components/Asset/Status/AssetCardStatus.tsx
- client/src/components/Asset/Status/CardStatus.tsx
- client/src/screens/InitialSetting.tsx
> Asset & Card / Only account on connected card

- client/src/components/Asset/Status/CardStatus.tsx
- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/screens/Landing.tsx
- client/src/screens/User.tsx
- client/src/store/setting.ts
- client/src/store/user.ts
- client/src/util/api/settingAPI.ts
- client/src/util/api/userAPI.ts
> ChartSkin / Lock when unpaid

- server/controllers/settings.ts
> Settings / Fix USetting* API bug

- client/src/components/Payment/PaymentOverlay.module.css
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/constants/chart-skin.ts
> ChartSkin / Fix refresh select & Submit when selecte

- client/src/components/Payment/PaymentOverlay.module.css
- client/src/components/Payment/PaymentOverlay.tsx
> PaymentOverlay / Add refund policy

- client_admin/src/pages/UserPage/Index.js
- client_admin/src/pages/UserPage/tab/Challenges.js
- server/controllers/challenges.ts
- server/models/Chanllenge.ts
- server/routes/challenges.ts
- server/routes/index.ts
> Challenge / Create model, create API, read API, admin pages

- server/controllers/settings.ts
- server/models/User.ts
> User / Implement theme settings

- server/controllers/transactions.ts
> Transactions / Enable to find by tag

- server/controllers/settings.ts
- server/models/_basicSettings.ts
> User / change default chartSkin setting basic to cat 

- client/src/components/Asset/Editor/AssetCardItemEditor.tsx
- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Asset/Editor/PaymentEditor.tsx
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Payment/PaymentOverlay.tsx
- client/src/components/UI/EmojiOverlay.tsx
- client/src/components/UI/Overlay.tsx
- client/src/components/User/Category/UserCategorySetting.tsx
- client/src/components/User/Info/Buisness.tsx
- client/src/components/User/Info/Developers.tsx
- client/src/components/User/Info/Privacy.tsx
- client/src/components/User/Info/Terms.tsx
- client/src/components/User/Profile/UserHeader.tsx
- client/src/components/User/Skin/ChartSkinSetting.tsx
> fix: Overlay / Close overlay on back navigateion #502

- client/src/components/Budget/Category/CategoryPlanItem.tsx
> fix: CategoryPlan / Fix category plan input showing previous input

- client/src/components/Budget/Category/CategoryPlan.module.css
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Input/EditInput.tsx
> CategoryPlan / Add over alert

- server/controllers/budgets.ts
- server/models/Budget.ts
> Budget / Add field `autoPlanned` in category

- server/controllers/settings.ts
- server/models/User.ts
- server/models/_basicSettings.ts
> User / Implement theme setting validation

- server/controllers/categories.ts
- server/models/Budget.ts
- server/routes/categories.ts
> User / Implement single category CRUD APIs

- client_admin/src/pages/UserBudgetPage/tab/TransactionList.js
> Admin / Handling transactions with undefined date

- client/src/components/Budget/Input/AmountInput.tsx
- client/src/components/Budget/Input/AmountOverlay.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> fix: AmountOverlay / Closed on edit & Update comma on backspace

- server/controllers/categories.ts
> User / Update single category C/U APIs

- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryAddOverlay.module.css
- client/src/components/Budget/Category/CategoryAddOverlay.tsx
- client/src/components/UI/EmojiInput.tsx
- client/src/index.tsx
- client/src/models/Category.ts
- client/src/screens/Budget.tsx
- client/src/store/ui.ts
- client/src/store/user-category.ts
- client/src/util/api/categoryAPI.ts
> Category / Create AddCategoryOverlay component

- server/controllers/budgets.ts
- server/controllers/categories.ts
- server/controllers/transactions.ts
- server/models/Budget.ts
- server/routes/budgets.ts
> Budget / Calculate budget amounts when reading budget

- client_admin/src/pages/UserBudgetPage/tab/Categories.js
- server/models/Budget.ts
> Budget / implement autoPlanned feature

- client/src/components/Budget/Amount/AmountBars.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanItem.module.css
- client/src/components/Budget/Category/CategoryPlanItem.tsx
- client/src/components/Budget/Input/AmountInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/models/Category.ts
- client/src/util/api/categoryAPI.ts
> feat: CategoryPlan / Add auto planning #527

- client/src/components/Budget/Amount/AmountBars.module.css
- client/src/components/Budget/Amount/AmountBars.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanItem.tsx
> feat: AmountBars / Update amount bar as vertical bar chart #541

- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionList.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
> BasicBudget / Date is set 1st when editting & Sorting bug & Rename: basic -> repeating #534

- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Input/AmountInput.tsx
- client/src/components/Budget/Input/AmountOverlay.tsx
- client/src/components/Budget/Input/EditInput.tsx
- client/src/components/User/Default/DefaultStatus.tsx
> fix: AmountInput / Handler input not exists #550

- client/src/components/Budget/Category/CategoryDetail.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
- client/src/components/Budget/UI/BudgetHeader.module.css
- client/src/components/Budget/UI/BudgetHeader.tsx
- client/src/components/User/Default/DefaultStatus.tsx
- client/src/screens/Budget.tsx
- client/src/util/api/budgetAPI.ts
> feat: BudgetHeader / Add delete option #479

- .github/workflows/server-v1-pipeline.yml
- .github/workflows/server-v2-pipeline.yml
- server/_passportConfig/localV2Strategy.ts
> Deploy / Use docker hub instead of ghcr

- .github/workflows/server-v2-pipeline.yml
> Infra / Replace EC2 Instance

- server/package.json
> Auth / Fix sending email bug

- client/src/App.tsx
- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/Store/AdRemove.module.css
- client/src/components/Store/AdRemove.tsx
- client/src/components/User/Skin/ChartSkinList.tsx
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/layout/Nav.tsx
- client/src/layout/Root.tsx
- client/src/screens/Store.module.css
- client/src/screens/Store.tsx
- client/src/screens/User.tsx
- client/src/store/ui.ts
> Feat: Store / Set store page #563

- client_admin/src/components/Navbar.js
- client_admin/src/pages/App.js
> Auth / Fix admin auth error - redirection, logout

- client_admin/src/pages/UserPage/tab/Payments.js
- server/controllers/payments.ts
- server/routes/payments.ts
> Payment / create DPayment API

- client_admin/src/pages/UserPage/tab/Payments.js
> Payments / Fix RPayments bug

- app/during/src/screens/Main.tsx
- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/Store/AdRemove.tsx
- client/src/components/User/Skin/ChartSkinList.tsx
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/constants/chart-skin.ts
- client/src/layout/Root.tsx
- client/src/screens/Landing.tsx
- client/src/screens/Store.tsx
- client/src/screens/User.tsx
> 570 platform

- app/during/src/screens/Main.tsx
- client/src/App.tsx
- client/src/layout/Root.tsx
- client/src/screens/Landing.tsx
- client/src/screens/User.tsx
> App / Get platform info from ReactNative

- client_admin/src/components/Detail.js
- server/models/Budget.ts
> Budget / Craete fileds `expensePlannedRemain`, `incomePlannedRemain`

- client/src/App.tsx
- client/src/components/Budget/Amount/AmountRing.tsx
- client/src/components/Budget/Category/CategoryDetail.tsx
- client/src/components/Budget/Category/CategoryLayout.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanItem.tsx
- client/src/components/Budget/Status/CategoryStatus.tsx
- client/src/index.tsx
- client/src/models/Budget.ts
- client/src/screens/Budget.tsx
- client/src/util/api/budgetAPI.ts
> AmountPlanned / Use value from server & Resolve force updating amountPlanned

- server/controllers/budgets.ts
> Budget / update autoPlanned to false when amountPlanned is updated #584

- server/controllers/users.ts
- server/models/User.ts
- server/routes/users.ts
> User / Implement agreement features

- client/src/layout/RequireAuth.tsx
- client/src/store/user.ts
> refactor: RequireAuth / Update login logic to set user data

- client/src/components/Asset/Editor/AssetCardItemEditor.module.css
- client/src/components/Asset/Editor/AssetFields.module.css
- client/src/components/Asset/List/AssetList.module.css
> Asset / CSS refactoring: global class + emotion 

- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> TransactionForm / Last date showing instead of previous date

- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/Budget/Transaction/TransactionDetail.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
- client/src/components/Budget/Transaction/TransactionItem.tsx
- client/src/components/Budget/Transaction/TransactionOption.tsx
- client/src/components/UI/button/OptionButton.tsx
- client/src/components/UI/overlay/Overlay.tsx
- client/src/components/User/Skin/ChartSkinList.tsx
> TransactionDetail / Transaction edit not working

- client/src/components/User/Skin/ChartSkinList.tsx
- client/src/components/User/Skin/ChartSkinSetting.module.css
- client/src/components/User/Skin/ChartSkinSetting.tsx
- client/src/layout/RequireAuth.tsx
> Fix: ChartSkin / Fix not setting error

- client/src/App.tsx
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Landing/AgreementOverlay.tsx
- client/src/components/UI/button/Button.tsx
- client/src/components/UI/button/ConfirmCancelButtons.tsx
- client/src/components/UI/overlay/Overlay.tsx
- client/src/components/User/Info/Privacy.tsx
- client/src/components/User/Info/Terms.tsx
- client/src/components/User/Profile/UserHeader.tsx
- client/src/components/User/Setting/SettingList.tsx
- client/src/constants/version.ts
- client/src/css/layout.css
- client/src/layout/Index.tsx
- client/src/layout/Layout.module.css
- client/src/layout/RequireAuth.tsx
- client/src/screens/InitialSetting.tsx
- client/src/screens/User.tsx
- client/src/store/user.ts
- client/src/util/api/userAPI.ts
> Agreement / Add terms & policy agreement overlay

- client/src/components/Asset/Editor/AssetCardListEditor.tsx
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/Budget/Transaction/TransactionForm.tsx
> Feat: Add AssetCardListEditor to TransactionForm #623

- client/src/components/Budget/Transaction/TransactionItem.tsx
- client/src/components/Budget/Transaction/TransactionList.module.css
> Fix: TransactionList / Add bottom padding for scroll

- client/src/components/UI/draggable/DraggableList.tsx
- client/src/components/User/Category/UserCategoryList.tsx
> Feat: UserCategoryList / Scroll on add

- client/src/components/User/Info/Privacy.tsx
- client/src/layout/Index.tsx
- client/src/screens/InitialSetting.tsx
- client/src/screens/NewBudget.tsx
- client/src/screens/User.tsx
- client/src/util/api/budgetAPI.ts
> Fix: AssetCard / Hide asset card page & initial setting

- client/src/components/Auth/AuthOverlay.tsx
- client/src/components/Auth/EmailForm.tsx
- client/src/components/Budget/UI/BudgetNav.tsx
- client/src/components/Landing/AgreementOverlay.tsx
- client/src/components/UI/overlay/Overlay.tsx
- client/src/layout/AuthRedirect.tsx
- client/src/layout/ErrorBoundary.tsx
- client/src/screens/InitialSetting.tsx
- client/src/screens/Landing.tsx
- client/src/screens/NewBudget.tsx
- client/src/screens/User.tsx
> Fix: Hash / Add base hash on navigate #641

- client/src/components/User/Profile/UserHeader.tsx
- client/src/screens/Budget.tsx
> Fix: UserHeader / Fix birthdate value format - YYYY-MM-DD

- server/@types/index.d.ts
- server/package.json
- server/src/api/controllers/users.ts
- server/src/api/middleware/validator.ts
- server/src/api/routes/agreements.ts
- server/src/api/routes/index.ts
- server/src/api/routes/users.ts
- server/src/api/services/agreement.ts
- server/src/api/services/user.ts
- server/src/errors/InvalidError.ts
- server/src/errors/NotFoundError.ts
- server/src/models/Agreement.ts
- server/src/models/User.ts
- server/src/models/UserAgreement.ts
- server/src/services/budgets/categories.ts
- server/src/services/challenges.ts
- server/src/services/payments.ts
- server/src/services/transactions.ts
- server/src/services/users/assets.ts
- server/src/services/users/auth.ts
- server/src/services/users/cards.ts
- server/src/services/users/categories.ts
- server/src/services/users/index.ts
- server/src/services/users/paymentMethods.ts
- server/src/services/users/settings.ts
- server/src/types/agreement.ts
- server/src/types/user.ts
- server/yarn.lock
> Agreement / create Agreement&UserAgreement tables

- server/src/api/controllers/auth.ts
- server/src/api/controllers/transactions.ts
- server/src/api/services/user.ts
- server/src/models/User.ts
- server/src/services/budgets/index.ts
- server/src/types/user.ts
> User / convertToUser 개선

- client/src/components/Budget/Input/AmountOverlay.module.css
- client/src/components/Budget/Input/AmountOverlay.tsx
- client/src/layout/Root.tsx
- client/src/store/ui.ts
> Feat: AmountOverlay / Prevent some operator on first input & shake when error

- client/src/components/Budget/Input/DateInput.tsx
- client/src/util/date.ts
> fix: DateInput / Limit dateinput & add time

- client/src/components/Asset/Editor/AssetCardEditItemList.module.css
- client/src/components/Asset/Editor/AssetCardListEditor.module.css
- client/src/components/Asset/Editor/PaymentEditor.module.css
- client/src/components/Budget/Amount/AmountDetail.tsx
- client/src/components/Budget/Amount/AmountDetailItem.module.css
- client/src/components/Budget/Category/BudgetCategorySetting.module.css
- client/src/components/Budget/Category/BudgetCategorySetting.tsx
- client/src/components/Budget/Category/CategoryPlan.module.css
- client/src/components/Budget/Category/CategoryPlan.tsx
- client/src/components/Budget/Category/CategoryPlanItem.module.css
- client/src/components/Budget/Category/CategoryPlanItem.tsx
- client/src/components/Budget/Status/TotalStatus.tsx
- client/src/components/UI/draggable/DraggableItem.tsx
- client/src/components/User/Category/UserCategoryList.module.css
- client/src/components/User/Category/UserCategorySetting.tsx
- client/src/css/_reset.css
> CategoryPlan, TotalStatus / Adjust UI size 

- client/src/components/Auth/AuthOverlay.tsx
- client/src/components/Budget/Input/AmountOverlay.tsx
- client/src/components/Budget/Input/CategoryInput.tsx
- client/src/components/Budget/Input/PaymentInput.tsx
- client/src/components/UI/overlay/OverlayForm.tsx
- client/src/screens/InitialSetting.tsx
- client/src/store/ui.ts
- client/src/store/user.ts
> Overlay, InitialSetting, PaymentInput / Fix bug

- server/src/services/users/settings.ts
> Server / Fix findChartSkinOptionsPaid method

- server/@types/env.d.ts
- server/package.json
- server/src/api/controllers/items.ts
- server/src/api/controllers/payments.ts
- server/src/api/controllers/test.ts
- server/src/api/routes/items.ts
- server/src/api/routes/payments.ts
- server/src/api/routes/test.ts
- server/src/config/index.ts
- server/src/config/type.ts
- server/src/errors/ConfilicError.ts
- server/src/errors/NotFoundError.ts
- server/src/lib/googleAPIs.ts
- server/src/services/inAppProducts.ts
- server/src/services/items.ts
- server/src/services/payments.ts
> [Payment] [WIP] 인앱결제 서버로직 구현

- client/src/App.tsx
- client/src/components/Payment/PaymentOverlay.tsx
- client/src/components/Store/AdRemove.tsx
- client/src/screens/Store.tsx
- client/src/store/user.ts
- client/src/util/api/paymentAPI.ts
- client/src/util/api/userAPI.ts
> feat: [PaymentAPI] Add completeByMoblieUser API #665

- client/src/App.tsx
- client/src/components/Payment/PaymentOverlay.tsx
- client/src/components/Store/AdRemove.module.css
- client/src/components/Store/AdRemove.tsx
- client/src/components/UI/overlay/OverlayForm.tsx
- client/src/components/User/Skin/ChartSkinList.tsx
- client/src/layout/PaymentRedirect.tsx
- client/src/screens/Store.module.css
- client/src/screens/Store.tsx
- client/src/store/ui.ts
- client/src/store/user.ts
> Payment / Pending & Apply item & AdRemove

- server/src/api/controllers/payments.ts
- server/src/api/controllers/test.ts
- server/src/api/routes/test.ts
- server/src/config/index.ts
- server/src/loaders/express.ts
- server/src/models/Item.ts
- server/src/models/_basicSettings.ts
- server/src/services/users/settings.ts
> Server / Item etc.

- server/src/models/_basicSettings.ts
- server/src/services/users/settings.ts
> [FIX] change basic chartSkin from "cat" to "basic"

- server/@types/env.d.ts
- server/package.json
- server/src/api/controllers/auth.ts
- server/src/api/middleware/auth.ts
- server/src/api/routes/auth.ts
- server/src/api/routes/develop.controller.ts
- server/src/api/routes/index.ts
- server/src/config/index.ts
- server/src/config/type.ts
- server/src/loaders/express.ts
- server/src/utils/crypto.ts
- server/yarn.lock
> Server / 실행 환경 수정

- server/src/api/routes/payments.ts
- server/src/app.ts
- server/src/lib/IAPHelper.ts
- server/src/services/payment.service.ts
- server/src/services/payments.ts
- server/src/tasks/index.ts
- server/src/tasks/syncPaymentCancellations.task.ts
- server/src/types/payment.ts
> InApp / 인앱 결제 환불 내역 처리
